//////////////////////////////////////////

  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.

//////////////////////////////////////////

= 密封的层次结构 (incubating)

密封类、接口和特征限制了哪些子类可以扩展/实现它们。在密封类出现之前，类层次结构设计者有两个主要选择：

* 将class设置为final, 不允许继承
* 将class设置为public, 非final, 运行任何人继承

与这些全有或全无的选择相比，密封类提供了一个中间立场。

例如，假设我们要创建一个仅包含圆形和正方形的形状层次结构。我们还希望形状接口能够引用层次结构中的实例。我们可以按如下方式创建层次结构：
[source,groovy]
----
include::../../test/SealedSpecificationTest.groovy[tags=simple_interface_keyword,indent=0]
----

Groovy 还支持替代注解语法。我们认为关键字样式更好，但如果您的编辑器尚不支持 Groovy 4，您可以选择注解样式。
[source,groovy]
----
include::../../test/SealedSpecificationTest.groovy[tags=simple_interface_annotations,indent=0]
----

我们可以有一个 ShapeI 类型的引用，由于 permits 子句，它可以指向 Circle 或 Square ，并且，由于我们的类是 final ，我们知道将来不会将其他类添加到我们的层次结构中。

一般来说，我们可能希望立即锁定类层次结构的某些部分，就像我们在这里将子类标记为 final 但其他时候我们可能希望允许进一步控制继承。

[source,groovy]
----
include::../../test/SealedSpecificationTest.groovy[tags=general_sealed_class,indent=0]
----

.<单击查看备用注解语法>
[%collapsible]
====
[source,groovy]
----
include::../../test/SealedSpecificationTest.groovy[tags=general_sealed_class_annotations,indent=0]
----
====

&nbsp; +
在此示例中， Shape 允许的子类是 Circle 、 Polygon 和 Rectangle 。 Circle 是 final ，因此层次结构的该部分无法扩展。

Polygon 是隐式非密封， RegularPolygon 显式标记为 non-sealed 。这意味着我们可以通过子类进行任何进一步的扩展，如 `Polygon → RegularPolygon` 和 `RegularPolygon → Hexagon` 所示。

`Rectangle` 是密封的，并且仅允许 Square 子类。

密封类对于创建需要包含实例特定数据的类似枚举的相关类非常有用。例如，我们可能有以下枚举：

[source,groovy]
----
include::../../test/SealedSpecificationTest.groovy[tags=weather_enum,indent=0]
----

但我们现在还希望将天气特定数据添加到天气预报中。我们可以按如下方式改变我们的抽象：

[source,groovy]
----
include::../../test/SealedSpecificationTest.groovy[tags=weather_sealed,indent=0]
----

在指定代数(Algebraic)或抽象数据类型(Abstract Data Types) (ADT) 时，密封层次结构也很有用，如下例所示：

[source,groovy]
----
include::../../test/SealedSpecificationTest.groovy[tags=sealed_ADT,indent=0]
----

密封层次结构与Record类也可以配合使用，如以下示例所示：

[source,groovy]
----
include::../../test/SealedSpecificationTest.groovy[tags=sealedRecord_ADT,indent=0]
----

== 与 Java 的差异

* Java provides no default modifier for subclasses of sealed classes
and requires that one of `final`, `sealed` or `non-sealed` be specified.
Groovy defaults to _non-sealed_ but you can still use `non-sealed/@NonSealed` if you wish.
We anticipate the style checking tool CodeNarc will eventually have a rule that
looks for the presence of `non-sealed` so developers wanting that stricter
style will be able to use CodeNarc and that rule if they want.

* 目前，Groovy 不会检查 permittedSubclasses 中提到的所有类在编译时是否可用并与基本密封类一起编译。这可能会在 Groovy 的未来版本中发生变化。

Groovy支持 native封闭类, 也支持通过注解将class标记为封闭类

@SealedOptions 注解支持 mode 注解属性，该属性可以采用三个值之一（ AUTO 为默认值）：

NATIVE::
Produces a class similar to what Java would do.
Produces an error when compiling on JDKs earlier than JDK17.
EMULATE::
Indicates the class is sealed using the `@Sealed` annotation.
This mechanism works with the Groovy compiler for JDK8+ but is not recognised by the Java compiler.
AUTO::
Produces a native record for JDK17+ and emulates the record otherwise.

Whether you use the `sealed` keyword or the `@Sealed` annotation
is independent of the mode.
