//////////////////////////////////////////

  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.

//////////////////////////////////////////
ifndef::core-operators[]
:core-operators: core-operators.adoc
endif::[]
ifndef::core-semantics[]
:core-semantics: core-semantics.adoc
endif::[]

= 语法

本章将覆盖Groovy编程语言的语法。 Groovy语言的语法是由JAVA语言的语法衍生出来, 但具体结构上会有所增强，同时容许一定的简化。

== 注释

=== 单行注释
单行注释以 `//` 开始，同时它可以出现在行的任何地方。 在 `//` 之后的字符, 一直到行尾都是注释的部分。
[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=single_line_comment,indent=0]
----

=== 多行注释

一个多行的注释以 `/*` 开头，同时它可以出现在行的任何地方。

在 `/\*` 之后的字符将会被视作注释的一部分，包括新一行的字符, 直到第一个 `*/` 来结束注释。

多行注释因此可以被放到行尾，或者甚至在句子中间。

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=multiline_comment,indent=0]
----

=== 文档注释
与多行注释类似，文档注释是多行的，但是是以 `/\**` 开始和以 `*/` 结尾。 在第一行GroovyDoc注释之后的行可以可选地以 `*`开头。 这些注释的组成有：

* 类型定义（类，接口，枚举，注解）

* 字段和属性定义

* 方法定义

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=groovydoc_comment,indent=0]
----
Groovy文档注释遵循与Java文档注释一样的约定。 所以你可以使用与Java文档注释一样的tags

另外, Groovy从3.0.0开始支持 *运行时文档注释*. 运行时文档注释可以在运行时保留.


NOTE: Groovy运行时文档注释默认不启用. 可以通过添加JVM参数 `-Dgroovy.attach.runtime.groovydoc=true` 来启用它Runtime


运行时文档注释以 `/\**@` 开始, 以 `*/` 结束, 例如:

[source,groovy]
----
/**@
 * Some class groovydoc for Foo
 */
class Foo {
    /**@
     * Some method groovydoc for bar
     */
    void bar() {
    }
}

assert Foo.class.groovydoc.content.contains('Some class groovydoc for Foo') // <1>
assert Foo.class.getMethod('bar', new Class[0]).groovydoc.content.contains('Some method groovydoc for bar') // <2>
----
<1> 获取类 `Foo` 上的运行时文档注释
<2> 获取方法 `bar` 上的运行时文档注释

=== shebang行

除了单行注释外，还有一种特殊的行注释，在UNIX 系统中通常被称为  _shebang_ 行，允许脚本直接从命令行运行，前提是你已安装了 Groovy 发行版并且 `groovy` 命令在 `PATH` 上可用。

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=shebang_comment_line,indent=0]
----

NOTE: `#` 字符必须是文件的第一个字符。 任何缩进都会引起一个编译错误。

== 关键字

下面的列表列出了全部Groovy语言的保留关键字:

[cols="1,1,1,1"]
.保留关键字
|===
include::../../test/SyntaxTest.groovy[tags=reserved_keywords,indent=0]
|===

其中，`const` 、`goto` 、`strictfp` 和 `threadsafe` 目前没有在使用中。

一般情况下，保留关键字不能用作变量、字段和方法名。

****
将方法名用引号括起来, 允许定义具有与关键字相同名称的方法, 如下所示:

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=reserved_keywords_example,indent=0]
----

使用这样的名称可能会令人困惑，通常最好避免使用。
这个技巧主要是为了在特定的Java集成场景和特定link:../core-domain-specific-languages.html[DSL] 场景实现一些希望使用与关键字相同名称的“动词”和“名词”的情况。
****


此外，Groovy 还具有以下上下文关键字：

[cols="1,1,1,1"]
.Contextual Keywords
|===
include::../../test/SyntaxTest.groovy[tags=contextual_keywords,indent=0]
|===

这些单词只在特定上下文中成为关键字，并且在某些地方可以更自由地使用，特别是在变量、字段和方法名中。

****
这些额外的宽松性允许我们使用在较早版本的Groovy中不是关键字，或者在Java中也不是关键字的单词来作为变量名, 示例如下:


[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=contextual_keywords_examples,indent=0]
----
熟悉这些上下文关键字的Groovy程序员可能仍然希望避免使用这些名称，除非有充分的理由要使用这样的名称。
****

对于保留关键字的限制也适用于原始类型、布尔字面量和空字面量（这些稍后会进行讨论）：

[cols="1,1,1,1"]
.其他保留关键字
|===
include::../../test/SyntaxTest.groovy[tags=reserved_words,indent=0]
|===

****
虽然不建议，但可以使用与保留关键字相同的技巧：
[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=reserved_words_example,indent=0]
----
将这些单词用作方法名可能会引起混淆，通常最好避免使用。
然而，对于某些 link:../core-domain-specific-languages.html[DSLs] 来说，这可能是有用的。
****

== 标识符

=== 普通标识符

标识符以字母，美元符或下划线开头。不能以数字开头

字母可以是以下的范围:

* 'a' to 'z' (小写 ascii 字母)
* 'A' to 'Z' (大写 ascii 字母)
* '\u00C0' to '\u00D6'
* '\u00D8' to '\u00F6'
* '\u00F8' to '\u00FF'
* '\u0100' to '\uFFFE'

之后的字符可以包含字母和数字。

以下是一些有效标识符的示例（变量名）：

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=valid_identifiers,indent=0]
----

但以下的是不合法的标识符:

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=invalid_identifiers,indent=0]
----

所有跟在点号后的关键字也是合法的标识符:

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=keywords_valid_id_after_dot,indent=0]
----

=== 带引号的标识符

带引号标识符出现在点号表达式的点号之后.
例如，`person.name` 表达式中 `name` 部分就可以通过引号引起来成为 `person."name"` 或 `person.'name'` .
有趣的是，当某些标识符包含Java语言规范中禁止的非法字符，引号引起来后在Groovy就会被容许。 例如，像一个破折号，空格，感叹号等字符。


[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=quoted_id,indent=0]
----

正如我们在 <<all-strings,strings>> 中看到的, Groovy提供不同的字符串字面量。 所有跟着点号的字符串都是被允许的：

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=quoted_id_with_all_strings,indent=0]
----

正如下面的例子，纯字符的字符串和Groovy的GStings（字符串插值）的区别是，计算整个标识符时，插入的字符值是被插入到最终字符串:

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=quoted_id_with_gstring,indent=0]
----

[[all-strings]]
== 字符串

字符以链的形式形成的文本被称作字符串。 Groovy容许你实例化 `java.lang.String` 对象，以及在其他语言中被称作 _插值字符串_ （interpolated strings）的GStrings (`groovy.lang.GString`)


=== 单引号字符串

单引号字符串是一系列被单引号引起来的字符：

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=string_1,indent=0]
----

NOTE: 单引号括起的字符串是普通的 `java.lang.String` ，不支持插值。

=== 字符串连接

所有Groovy的字符串都可以用 `+` 号连接起来：

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=string_plus,indent=0]
----

=== 三单引号字符串

三引号字符串是一系列被三个单引号引起来的字符：

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=triple_single_0,indent=0]
----

NOTE: 单引号括起的字符串是普通的 `java.lang.String` ，不支持插值。

三引号字符串可以是多行的。 你不必将字符串分割成几块，也不必用连接符或换行符转义字符来将字符串跨行：:

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=triple_single_1,indent=0]
----

如果你的代码是缩进的，比如在类里面的方法，你的字符串将会包含这些空白的缩进。 Groovy开发套件提供 `String#stripIndent()` 方法来剥离（stripping out）缩进， 同时Groovy开发套件提供 `String#stripMargin()` 方法，该方法需要一个分隔符来识别从字符串的开头开始删除的文本。

当创建如下的字符串时:

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=triple_single_2,indent=0]
----

你会发现，得到的是一个以换行符开头的字符串。可以通过反斜杠转义换行来剥离该字符：

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=triple_single_3,indent=0]
----

==== 转义特殊字符串

你可以用反斜杠来转义单引号来避免终止字符串：

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=string_2,indent=0]
----

同时你可以用两个反斜杠转义转义符号本身：

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=string_3,indent=0]
----

一些特殊的字符串都是用反斜杠来作为转义字符：

[cols="1,2" options="header"]
|====
|Escape sequence
|Character

|\b
|backspace

|\f
|formfeed

|\n
|newline

|\r
|carriage return

|\s
|single space

|\t
|tabulation

|\\
|backslash

|\'
|single quote within a single-quoted string (and optional for triple-single-quoted and double-quoted strings)

|\"
|double quote within a double-quoted string (and optional for triple-double-quoted and single-quoted strings)
|====

当涉及到后面讨论的其他类型的字符串时，我们将看到一些更多的转义细节。

==== Unicode转义序列

对于不存在你键盘上的字符，你可以使用Unicode转义序列：反斜杠，然后是u，然后4个十六进制数字。

例如，欧元货币符号可以表示为：

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=string_4,indent=0]
----

=== 双引号字符串

双引号字符串是一系列被双引号引起来的字符：

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=string_5,indent=0]
----

NOTE: 如果没有插值表示式的话，双引号字符串就是 `java.lang.String`  ， 但如果有插值存在的话，双引号字符串就是一个 `groovy.lang.GString` 实例。

NOTE: 为了转义一个双引号，你可以用反斜杠符号：+"A double quote: \""+.


==== 字符串插值

除了单引号和三引号字符串,任何Groovy表达式都可以插值到所有的字符串里。
插值就是当计算字符串的值时，用值替换掉字符串中的占位符。


占位符表达式被 ${} 包围。在涉及到明确的点表达式时，大括号可以省略，也就是在这些情况下我们可以只使用 $ 前缀。

当一个GString被传递到一个需要String参数的方法时, 在占位符中的表达式会被转换为他的字符串值 (通过在表达式上调用 `toString()`), 然后将整个String传递到方法中


在这里，我们有一个带占位符的字符串，这个占位符引用一个本地变量:

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=gstring_1,indent=0]
----

然而任何的Groovy表达式都是有效的，正如我们看到的这个例子，它带有一个算术表达式:

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=gstring_2,indent=0]
----

[NOTE]
不但表达式在${}占位符里面是合法的。语句也同样是合法的，但语句的值为 `null` 。
所以如果有多个语句在占位符里面，最后的那个语句应该返回一个有意义的值，以便替换整个占位符的值。
例如， +"The sum of 1 and 2 is equal to ${def a = 1; def b = 2; a + b}"+ 是可以工作的，但一个好的做法通常是在GString里面的占位符内的表达式应该尽量简单。


除了 ${} 占位符之外，我们还可以使用独立的 $ 符号作为点表达式的前缀:

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=gstring_3,indent=0]
----

但是，只有形式为 `a.b` 、`a.b.c` 等的点表达式是有效的。

Expressions containing parentheses like method calls,
curly braces for closures, dots which aren't part of a property expression or arithmetic operators would be invalid.

给定如下的变量定义


[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=gstring_4,indent=0]
----

下面的句子会抛出一个 `groovy.lang.MissingPropertyException` 异常，因为Groovy认为你试图访问这个数字的 `toString` 这个不存在的属性：

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=gstring_5,indent=0]
----

NOTE: 你可以将 `"$number.toString()"` 想象为被解析器解释执行为 `"${number.toString}()"` .

类似地，如果表达式存在歧义，你需要保留大括号：

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=gstring_3b,indent=0]
include::../../test/SyntaxTest.groovy[tags=gstring_3b2,indent=0]
include::../../test/SyntaxTest.groovy[tags=gstring_3b3,indent=0]
----

如果需要在 GString 中转义 `$` 或 `${}` 占位符，使它们显示而不发生插值，只需要使用 `\` 反斜杠字符来转义美元符号：

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=gstring_6,indent=0]
----

==== 插值闭包表达式的特殊情况

到目前为止，我们已经看到，我们可以插任意值到 `${}` 占位符，但这里有一个特殊情况就是闭包表达式。 当占位符包含一个箭头，`${→}` ,这个表达式事实上是一个闭包表达式 -- 你可以把它看作是一个带有美元符前缀的闭包：

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=closure_in_gstring_1,indent=0]
----
<1> 这个闭包是一个不带参数的无参闭包。
<2> 在这里，闭包接受一个 `java.io.StringWriter` 参数，你可以用 `<<` 左移运算符添加内容。

在任一情况下，这两个占位符都是嵌套的闭包。

从表面上看，它看起来像是一种定义要插值的表达式的更详细的方式，但闭包比单纯的表达式有一个有趣的优点：惰性求值。

让我们考虑以下示例：

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=closure_in_gstring_2,indent=0]
----
<1> 我们定义一个包含 1 的 number 变量，然后将其插入两个 GString 中，作为 eagerGString 中的表达式和 lazyGString 中的闭包。
<2> 我们期望结果字符串包含与 eagerGString 相同的字符串值 1。
<3> 对于 lazyGString 也是如此
<4> 然后我们将变量的值更改为新数字
<5> 对于简单的插值表达式，该值实际上是在创建 GString 时绑定的。
<6> 但使用闭包表达式时，每次将 GString 强制转换为 String 时都会调用闭包，从而生成包含新数值的更新字符串。
[NOTE]
带有多个参数的嵌入式闭包表达式将在运行时生成异常。只允许带有零个或一个参数的闭包。

==== 与Java的互操作性

当一个方法（无论是用 Java 还是 Groovy 实现）需要一个 java.lang.String ，但我们传递一个 groovy.lang.GString 实例时，GString 的 toString() 方法会自动且透明地执行叫。
[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=java_gstring_interop_1,indent=0]
----
<1> 我们创建一个 GString 变量
<2> 我们仔细检查它是 GString 的实例
<3> 然后我们将该 GString 传递给以 String 作为参数的方法
<4> takeString() 方法的签名明确表示其唯一参数是字符串
<5> 我们还验证该参数确实是一个 String 而不是 GString。

==== GString和String的hashCodes

尽管可以使用插值字符串代替普通 Java 字符串，但它们在特定方面与字符串不同：它们的 hashCode 不同。普通 Java 字符串是不可变的，而 GString 的结果字符串表示形式可能会有所不同，具体取决于其插值。即使对于相同的结果字符串，GString 和 String 也不具有相同的 hashCode。

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=gstring_hashcode_1,indent=0]
----

GString 和 String 具有不同的 hashCode 值，应避免使用 GString 作为 Map 键，特别是当我们尝试使用 String 而不是 GString 检索关联值时。

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=gstring_hashcode_2,indent=0]
----
<1> 该映射是使用一个初始对创建的，其键是 GString
<2> 当我们尝试使用 String 键获取值时，我们将找不到它，因为 String 和 GString 具有不同的 hashCode 值

=== 三双引号字符串

三重双引号字符串的行为类似于双引号字符串，此外它们是多行的，就像三重单引号字符串一样。

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=triple_double_1,indent=0]
----

NOTE: 双引号和单引号都不需要在三重双引号字符串中进行转义。

=== 斜杠字符串

除了通常的带引号的字符串之外，Groovy 还提供斜杠字符串，它使用 / 作为开始和结束分隔符。斜杠字符串对于定义正则表达式和模式特别有用，因为不需要转义反斜杠。

斜杠字符串的示例：

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=slashy_1,indent=0]
----

只有正斜杠需要用反斜杠转义：

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=slashy_2,indent=0]
----

斜杠字符串是多行的：

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=slashy_3,indent=0]
----

Slashy 字符串可以被认为是定义 GString 的另一种方式，但具有不同的转义规则。因此它们支持插值：
[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=slashy_4,indent=0]
----

==== 特殊情况

空的斜杠字符串不能用双正斜杠表示，因为 Groovy 解析器将其理解为行注释。这就是为什么以下断言实际上不会编译，因为它看起来像一个非终止语句：

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=slashy_5,indent=0]
----

由于斜线字符串主要是为了使正则表达式更容易而设计的，因此 GString 中的一些错误（例如 $() 或 $5 ）将适用于斜线字符串。

请记住，转义反斜杠不是必需的。另一种思考方式是，实际上不支持转义。斜杠字符串 `/\t/` 不会包含制表符，而是包含反斜杠，后跟字符“t”。仅允许转义正斜杠，即 `/\/folder/` 将是包含 `'/folder'` 的斜杠字符串。

转义正斜杠的结果是斜杠字符串不能以反斜杠结尾。否则将会转义斜杠字符串终止符。您可以使用特殊技巧 `/ends with slash ${'\'}/` 。但在这种情况下最好避免使用斜线。

=== 美元符斜杠字符串

美元斜线字符串是用开头 $/ 和结尾 /$ 分隔的多行 GString。转义字符是美元符号，它可以转义另一个美元或正斜杠。仅当与美元和正斜杠字符的特殊使用发生冲突时才需要对这些字符进行转义。字符 $foo 通常表示 GString 占位符，因此可以通过转义美元将这四个字符输入到美元斜线字符串中，即 $$foo 。同样，如果您希望美元斜线结束分隔符出现在字符串中，则需要对其进行转义。

这里有一些例子：

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=dollar_slashy_1,indent=0]
----

It was created to overcome some of the limitations of the slashy string escaping rules.
Use it when its escaping rules suit your string contents (typically if it has some slashes you don't want to escape).

=== 字符串汇总表

[cols="5*", ptions="header"]
|====
|字符串名称
|字符串格式
|是否支持插值
|是否支持多行
|转义字符

|单引号
|`'...'`
|icon:check-empty[]
|icon:check-empty[]
|`\`

|三单引号
|`'''...'''`
|icon:check-empty[]
|icon:check[]
|`\`

|双引号
|`"..."`
|icon:check[]
|icon:check-empty[]
|`\`

|三双引号
|`"""..."""`
|icon:check[]
|icon:check[]
|`\`

|斜杠字符串
|`/.../`
|icon:check[]
|icon:check[]
|`\`

|美元斜杠字符串
|`$/.../$`
|icon:check[]
|icon:check[]
|`$`
|====

=== 字符

与 Java 不同，Groovy 没有显式的字符文字。但是，您可以通过三种不同的方式明确将 Groovy 字符串设置为实际字符：

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=char,indent=0]
----
<1> 通过在声明保存字符的变量时明确指定 char 类型
<2> 通过使用 as 运算符进行类型强制转换
<3> 通过使用强制转换为字符操作


include::_working-with-numbers.adoc[leveloffset=+1]

== 布尔类型

布尔值是一种特殊的数据类型，用于表示真假： true 和 false 。将此数据类型用于表示真/假<<{core-operators}#Operator-Overloading,条件>>的简单标志。


布尔值可以存储在变量中，分配到字段中，就像任何其他数据类型一样：

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=variable_store_boolean_value,indent=0]
----

true 和 false 是仅有的两个原始布尔值。但更复杂的布尔表达式可以使用<<{core-operators}#logical_operators,逻辑运算符>>来表示。


此外，Groovy 有特殊规则（通常称为 Groovy Truth）用于将非布尔对象强制为布尔值。

== Lists

Groovy 使用逗号分隔的值列表（用方括号括起来）来表示列表。 Groovy 列表是普通的 JDK java.util.List ，因为 Groovy 没有定义自己的集合类。定义列表文字时使用的具体列表实现默认为 java.util.ArrayList ，除非您决定另外指定，我们稍后会看到。

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=list_1,indent=0]
----
<1> 我们定义一个由逗号分隔并用方括号括起来的列表数字，并将该列表分配给一个变量
<2> 该列表是 Java 的 java.util.List 接口的实例
<3> 可以使用 size() 方法查询列表的大小，并显示我们的列表包含 3 个元素

在上面的示例中，我们使用了元素类型相同的列表，但您也可以创建包含异构类型的列表：

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=list_2,indent=0]
----
<1> 我们这里的列表包含一个数字、一个字符串和一个布尔值


我们提到，*默认情况下，列表文字实际上是 `java.util.ArrayList` 的实例，但由于使用 `as` 运算符的类型强制，可以为列表使用不同的支持类型，或者使用变量的显式类型声明：*

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=coercion_of_list,indent=0]
----
<1> 我们使用带有 as 运算符的强制来显式请求 java.util.LinkedList 实现
<2> 保存列表文字的变量是 java.util.LinkedList 类型

您可以使用 [] 下标运算符（用于读取和设置值）使用正索引或负索引访问列表的元素，以访问列表末尾的元素以及范围，并使用 << leftShift 运算符将元素追加到列表中：

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=subscript_and_leftshift,indent=0]
----
<1> 访问列表的第一个元素（从零开始计数）
<2> 使用负索引访问列表的最后一个元素：-1 是列表末尾的第一个元素
<3> 使用赋值为列表的第三个元素设置新值
<4> 使用 << leftShift 运算符将元素追加到列表末尾
<5> 一次访问两个元素，返回包含这两个元素的新列表
<6> 使用范围访问列表中从开始到结束元素位置的一系列值

由于列表本质上可以是异构(heterogeneous )的，因此列表还可以包含其他列表来创建多维列表：

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=multi_dim_list,indent=0]
----
<1> 定义数字列表
<2> 访问最顶层列表的第二个元素和内部列表的第一个元素

== Arrays

*Groovy 使用了 List 的表示法来表示数组，但是要创建数组，您需要通过强制或类型声明来显式定义数组的类型。*

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=array_1,indent=0]
----
<1> 使用显式变量类型声明定义字符串数组
<2> 断言我们创建了一个字符串数组
<3> 使用 as 运算符创建一个整数数组
<4> 断言我们创建了一个原始整数数组

您还可以创建多维数组：

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=array_2,indent=0]
----
<1> 您可以定义新数组的边界
<2> 或者声明一个数组而不指定其边界


对数组元素的访问遵循与列表相同的表示法：

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=array_3,indent=0]
----
<1> 检索数组的第一个元素
<2> 将数组第三个元素的值设置为新值

=== Java风格的数组初始化

Groovy 始终支持使用方括号的列表/数组定义，并避免使用 Java 风格的大括号，以免与闭包定义冲突。然而，如果大括号紧跟在数组类型声明之后，则闭包定义不会产生歧义，因此 Groovy 3 及更高版本支持 Java 数组初始化表达式。

Examples:

[source,groovy]
--------------------------------------
def primes = new int[] {2, 3, 5, 7, 11}
assert primes.size() == 5 && primes.sum() == 28
assert primes.class.name == '[I'

def pets = new String[] {'cat', 'dog'}
assert pets.size() == 2 && pets.sum() == 'catdog'
assert pets.class.name == '[Ljava.lang.String;'

// traditional Groovy alternative still supported
String[] groovyBooks = [ 'Groovy in Action', 'Making Java Groovy' ]
assert groovyBooks.every{ it.contains('Groovy') }
--------------------------------------


== Maps

在其他语言中有时称为字典或关联数组，它具有映射功能。

映射将键与值关联起来，用冒号分隔键和值，每个键/值对用逗号分隔，整个键和值用方括号括起来。

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=map_def_access,indent=0]
----
<1> 我们定义一个字符串颜色名称的映射，与其十六进制编码的 html 颜色相关联
<2> 我们使用下标表示法来检查与 red 键关联的内容
<3> 我们还可以使用属性符号来断言绿色的十六进制表示
<4> 类似地，我们可以使用下标符号来添加新的键/值对
<5> 或者通过属性符号，添加 yellow 颜色

[NOTE]
When using names for the keys, we actually define string keys in the map.

[NOTE]
Groovy 创建的map实际上是 `java.util.LinkedHashMap` 的实例。

如果您尝试访问map中不存在的key：

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=unknown_key,indent=0]
----

您将获得 null 。

在上面的示例中，我们使用了字符串作为key，但您也可以使用其他类型的值作为键：

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=number_key,indent=0]
----

在这里，我们使用数字作为键，因为数字可以明确地被识别为数字，因此 Groovy 不会像我们前面的示例中那样创建字符串键。但考虑一下您想要传递变量代替键的情况，以使该变量的值成为键：

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=variable_key_1,indent=0]
----
<1> 与 'Guillaume' 名称关联的 key 实际上是 "key" 字符串，而不是与 key 变量关联的值
<2> map不包含 'name' 键
<3> 相反，map包含一个 'key' 键

[NOTE]
您还可以传递带引号的字符串和键：+[“name”：“Guillaume”]+。如果您的密钥字符串不是有效的标识符，则这是强制性的，例如，如果您想创建一个包含破折号的字符串密钥，如：+[“street-name”：“Main street”]+。

当您需要将变量值作为映射定义中的键传递时，必须用括号将变量或表达式括起来：

[source,groovy]
----
include::../../test/SyntaxTest.groovy[tags=variable_key_2,indent=0]
----

<1> 这次，我们用括号将 key 变量括起来，以指示解析器我们传递变量而不是定义字符串键
<2> 该map确实包含 name 键
<3> 但map不像以前那样包含 key 键
