//////////////////////////////////////////

  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.

//////////////////////////////////////////

= Closures

:lambdas: https://docs.oracle.com/javase/tutorial/java/javaOO/lambdaexpressions.html[lambda expressions in Java 8]

本章介绍 Groovy 闭包。 Groovy 中的闭包是一个开放的、匿名的代码块，可以接受参数、返回值和分配给变量。闭包可以引用在其周围范围内声明的变量。与闭包的正式定义相反，Groovy 语言中的 `Closure` 还可以包含在其周围范围之外定义的自由变量。虽然打破了闭包的正式概念，但它提供了本章中描述的各种优点。

== 语法
=== 定义闭包

闭包定义遵循以下语法：

[source,groovy]
-----------------------------------
{ [closureParameters -> ] statements }
-----------------------------------

其中 `+[closureParameters->]+` 是可选的以逗号分隔的参数列表，这些参数类似于方法参数列表，并且这些参数可以是类型化的或非类型化的。

statements是 0 个或多个 Groovy 语句。

当指定参数列表时， `+->+` 字符是必需的，用于将参数与闭包主体分隔开。_statements_ 部分由 0、1 或多个 Groovy 语句组成。


下面是一些合法的闭包定义:

[source,groovy]
-----------------------------------------------------------
include::../../test/ClosuresSpecTest.groovy[tags=closure_syntax_1,indent=0]

include::../../test/ClosuresSpecTest.groovy[tags=closure_syntax_1bis,indent=0]

include::../../test/ClosuresSpecTest.groovy[tags=closure_syntax_2,indent=0]

include::../../test/ClosuresSpecTest.groovy[tags=closure_syntax_3,indent=0]

include::../../test/ClosuresSpecTest.groovy[tags=closure_syntax_4,indent=0]

include::../../test/ClosuresSpecTest.groovy[tags=closure_syntax_5,indent=0]

include::../../test/ClosuresSpecTest.groovy[tags=closure_syntax_6,indent=0]
-----------------------------------------------------------
<1> 该闭包引用了名为 `item` 的变量
<2> 可以通过添加箭头 (`+->+`) 将闭包参数与代码显式分离
<3> 该闭包使用了隐式参数 (`it`)
<4> 另一种版本，其中 `it` 是显式参数
<5> 在这种情况下，通常最好为参数使用显式名称
<6> 接受两个类型参数的闭包
<7> 一个闭包可以包含多个语句

[[closure-as-object]]
=== 闭包作为对象

闭包是 `groovy.lang.Closure` 类的实例，可以像任何其他变量一样分配给变量或字段，尽管它是一个代码块：

[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=closure_is_an_instance_of_Closure,indent=0]
----
<1> 您可以将闭包分配给变量，它是 `groovy.lang.Closure` 的实例
<2> 如果不使用 `def` 或 `var` ，可以使用 `groovy.lang.Closure` 作为类型
<3> 或者，您可以使用 `groovy.lang.Closure` 的泛型类型指定闭包的返回类型

=== 调用闭包

闭包作为匿名代码块，可以像任何其他方法一样被调用。如果你定义一个不带参数的闭包，如下所示：

[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=closure_call_1,indent=0]
----

可以像方法一样通过变量来调用闭包, 只有在调用闭包时才会执行闭包内的代码:

[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=closure_call_1_direct,indent=0]
----

或者，您可以明确地使用 call 方法：

[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=closure_call_1_explicit,indent=0]
----

如果闭包接受参数，原理是相同的：

[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=closure_call_2,indent=0]
----
<1> 定义一个接受 `int` 作为参数的闭包
<2> 可以直接调用
<3> 或使用 `call` 方法
<4> 对于带有隐式参数 (`it`) 的闭包也是如此
<5> 可以直接使用 `(arg)` 调用
<6>  或使用 `call`

与方法不同，闭包在调用时 *总是* 返回一个值。下一节讨论如何声明闭包参数、何时使用它们以及什么是<<implicit-it,隐式
"it" 参数>>。


== 参数

=== 普通参数

闭包的参数遵循与常规方法的参数相同的原则：

* 可选类型
* 具有一个名字
* 具有可选的默认值

参数之间用逗号分隔：

[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=closure_param_declaration,indent=0]
----

[[implicit-it]]
=== 隐式参数

当闭包未显式定义参数列表（使用 `+->+` ）时，闭包 *始终* 定义一个隐式参数，名为 `it` 。这意味着这段代码：


[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=implicit_it,indent=0]
----

与此严格等效：

[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=implicit_it_equiv,indent=0]
----

如果你想声明一个不接受参数的闭包，并且必须限制为不带参数的调用，那么你 *必须* 使用显式的空参数列表来声明它：

[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=closure_no_arg_def,indent=0]

include::../../test/ClosuresSpecTest.groovy[tags=closure_no_arg_fail,indent=0]
----

=== 可变参数

闭包可以像任何其他方法一样声明变量参数。 如果最后一个参数具有可变长度, 或者是数组 , 那么闭包可以接受可变数量参数，如下例所示：


[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=closure_vargs,indent=0]
----
<1> 接受可变数量的字符串作为第一个参数
<2> 可以使用任意数量的参数调用它，而 *不必* 将它们显式包装到数组中
<3> 如果 _args_ 参数声明为数组，则可以直接使用相同的行为
<4> 只要 *最后一个* 参数是数组或显式 可变长度 类型

== 委托(Delegation)策略

=== Groovy 闭包与 lambda 表达式

Groovy 将闭包定义为 <<closure-as-object, Closure类的实例>>。它与  {lambdas} 非常不同。委托是 Groovy 闭包中的一个关键概念，而 lambda 中没有等效概念。_更改委托_ 或 _更改闭包的委托策略_ 的能力使得在 Groovy 中设计漂亮的领域特定语言 (DSL) 成为可能。


[[closure-owner]]
=== Owner, delegate 和 this

要理解delegate的概念，我们首先要解释一下闭包中 `this` 的含义。闭包实际上定义了 3 个不同的东西：

- `this` 对应于定义闭包的 _封闭类_
- `owner` 对应于定义闭包的 _封闭对象_ ，可以是类，也可以是闭包
- `delegate` 对应于第三方对象,  当闭包的调用者未定义时，方法调用或属性将被解析到 `delegate`。

[[closure-this]]
==== 闭包中的this

在闭包中，调用 `getThisObject` 将返回定义闭包的封闭类。它相当于使用显式 `this` ：

[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=closure_this,indent=0]
----
<1> 在 `Enclosing` 类中定义，并返回 `getThisObject`
<2> 调用闭包将返回定义闭包的 `Enclosing` 实例
<3> 一般来说，只会使用快捷方式 `this`
<4> 它返回 *完全* 相同的对象
<5> 如果闭包是在内部类中定义的
<6> 闭包中的 `this` 将返回内部类，而不是顶级类
<7> 在嵌套闭包的情况下，就像这里 `cl` 被定义在 `nestedClosures` 范围内一样
<8> 那么 `this` 对应于最接近的外部类，而不是封闭的闭包！

当然可以通过这种方式从封闭类中调用方法：

[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=closure_this_call,indent=0]
----
<1> 闭包调用 `this` 上的 `toString` ，这实际上会调用封闭对象（即 `Person` 实例）上的 `toString` 方法

==== 闭包的Owner属性
闭包的 `owner` 与 <<closure-this,闭包中的this>> 的定义非常相似，但有一个细微的区别：它将返回直接封闭的对象，无论是闭包还是类：


[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=closure_owner,indent=0]
----
<1> 在 `Enclosing` 类中定义，并返回 `getOwner`
<2> 调用闭包将返回定义闭包的 `Enclosing` 实例
<3> 一般来说，您只想使用快捷方式 `owner` 表示法
<4> 它返回 *完全* 相同的对象
<5> 如果闭包是在内部类中定义的
<6> 闭包中的 `owner` 将返回 _内部类_，而不是顶级类
<7> 但在嵌套闭包的情况下，就像这里 `cl` 被定义在 `nestedClosures` 范围内一样
<8> 那么 `owner` 对应于封闭的闭包，与 `this` 是不同的对象！

==== 闭包的Delegate

可以使用 `delegate` 属性或调用 `getDelegate` 方法来访问闭包的委托。它是在 Groovy 中构建领域特定语言的强大概念。虽然 <<closure-this,this>> 和 <<closure-owner,owner>> 指的是闭包的词法范围，但 `delegate` 是闭包将使用的用户定义的对象。默认情况下，`delegate` 设置为 `owner `：

[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=delegate_is_owner,indent=0]
----
<1> 您可以调用 `getDelegate` 方法获取闭包的委托
<2> 或使用 `delegate` 属性
<3> 两者都返回相同的对象
<4> 这是封闭类或闭包
<5> 特别是在嵌套闭包的情况下
<6> `delegate` 将对应于 `owner`

闭包的委托可以更改为 *任何对象*。让我们通过创建两个类来说明这一点，这两个类不是彼此的子类，但都定义了一个名为 `name` 的属性：

[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=change_delegate_classes,indent=0]
----

然后我们定义一个闭包来获取委托上的 `name` 属性：

[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=change_delegate_closure,indent=0]
----

然后通过改变闭包的委托，可以看到目标对象发生了变化：

[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=change_delegate_asserts,indent=0]
----

此时，行为与在闭包的词法作用域中定义 `target` 变量没有什么不同：

[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=delegate_alernative,indent=0]
----

但是，他们存在重大差异：

* 在最后一个示例中，`target` 是从闭包内引用的局部变量
* 委托可以透明地使用，也就是说，无需在方法调用前添加 `delegate.` 前缀，如下一段所述。


==== Delegation策略

每当在闭包中，在没有显式设置调用者的情况下访问属性时，就会涉及委托策略：

[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=delegation_strategy_intro,indent=0]
----
<1> `name` 没有引用闭包词法范围内的变量
<2> 我们可以将闭包的委托更改为 `Person` 的实例
<3> 方法调用将会成功

此代码起作用的原因是 `name` 属性将在 `delegate` 对象上解析！这是解决闭包内的属性或方法调用的一种非常强大的方法。不需要设置显式的 `delegate.` , 即可进行调用，因为闭包的默认委托策略使得它如此。闭包实际上定义了多种您可以选择的解决策略：


* `Closure.OWNER_FIRST` 是 *默认策略*。如果 *owner* 存在属性/方法，则将调用它。如果没有，则使用`delegate`。

* `Closure.DELEGATE_FIRST` 首先使用 *delegate*，然后使用 *owner*

* `Closure.OWNER_ONLY` 只会解析 *owner* 的属性/方法查找, *delegate* 将被忽略。
* `Closure.DELEGATE_ONLY` 将仅解析 *delegate* 上的属性/方法查找： *owner* 将被忽略。
* `Closure.TO_SELF` 可供需要高级元编程技术并希望实现自定义解析策略的开发人员使用：解析不会针对 `owner` 或 `delegate` 进行，而仅针对闭包类本身进行。仅当您实现自己的 `Closure` 子类时才有意义。

让我们用以下代码来说明默认的“owner first”策略：

[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=closure_owner_first,indent=0]
----
<1> 为了便于说明，我们定义了一个引用 `name` 的闭包成员
<2> `Person` 和 `Thing` 类都定义了 `name` 属性
<3> 使用默认策略， `name` 属性首先在 `owner` 上解析
<4> 因此，如果我们将 `delegate` 更改为 `t` ，它是 `Thing` 的实例
<5> 结果没有变化： `name` 首先在闭包的 `owner` 上解析

然而，可以改变闭包的解析策略：

[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=closure_delegate_first,indent=0]
----

通过更改 `resolveStrategy` ，Groovy 会解析 "隐式 this" 引用的方式：在这种情况下，将首先在delegate中查找 `name` ，如果没有找到，在owner上查找。由于 `name` 在 `delegate(Thing 的实例)` 中定义的了, 因此使用该值。


"delegate first" 和 "delegate only" 或者 "owner first" 和 "owner only" 之间的区别可以通过如下来说明:

[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=delegate_only,indent=0]
----
<1> 对于  "owner first" ，delegate是什么都无所谓
<2> 对于 "delegate only", `p` 作为delegate可以成功
<3> 对于 "delegate only" , `t` 作为 delegate 会失败

在此示例中，我们定义了两个类，它们都具有 `name` 属性，但只有 `Person` 类声明了 `age` 。 `Person` 类还声明了一个引用 `age` 的闭包。我们可以将默认的解析策略从 "owner first" 更改为 "delegate only"。由于闭包的owner是 `Person` 类，因此我们可以检查delegate是否是 `Person` 的实例，则调用闭包是成功的，但是如果 delegate 是 `Thing` 的实例，它失败并返回 `groovy.lang.MissingPropertyException` 。尽管闭包是在 `Person` 类中定义的，但不使用owner。


NOTE: 有关如何使用此功能来开发 DSL 的全面说明可以在手册的 link:../core-domain-specific-languages.html[dedicated section of the manual]. 中找到。


==== Delegation策略 in the presence of metaprogramming

在描述 "owner first" 委托策略时，我们谈到使用owner的属性/方法（如果它 _存在_ ），否则使用delegate的相应属性/方法。还有一个类似的但与其相反 "delegate first" 的策略。与其使用 _存在_ 一词，不如使用 _处理_ 一词更为准确。这意味着对于 "owner first"，如果属性/方法存在于owner中，或者它具有 propertyMissing/methodMissing 钩子函数，则owner将处理成员访问。


我们可以通过对上一个示例进行稍微修改的版本来看到这一点：

[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=delegate_only_prop_missing,indent=0]
----

在此示例中，即使我们的 `Thing` 类实例（cl的最后一次使用中的delegate）没有 `age` 属性，但它通过其 `propertyMissing` 钩子函数处理丢失的属性, 意味着 `age` 将是 `-1`。


== GString 中的闭包

以下代码：

[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=gstring_eager_intro,indent=0]
----

该代码的行为正如您所期望的，但如果添加以下内容会发生什么：

[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=gstring_eager_outro,indent=0]
----

你会看到断言失败了！有两个原因：

* GString 仅延迟计算表达式的 `toString` 形式
* GString 中的语法 `${x}` 并 *不* 代表闭包，而是 `$x` 的表达式，这会在在创建 GString 时进行评估.

在我们的示例中， `GString` 是通过一个引用 `x` 的表达式来创建的。创建 GString 时， `x` 的值为1，so the `GString` is created with a value of 1。当触发断言时，通过使用 `toString` 将 `1` 转换为 `String` 。当我们将 `x` 更改为 `2` 时，我们确实更改了 `x` 的值，但它是另外一个对象，并且 GString 仍然引用旧的对象(1)。

TIP: `GString` 只有当他 _引用的值_ 是可变的时, `GString` 的 `toString` 形式才会改变。如果只是引用发生变化，则不会发生任何事情。

TIP: 可以理解为将 `x` 作为参数传递到了 `GString` 中, 只有 `x` 引用的对象发生了改变, `GString` 才会改变. 如果将其他值赋给 `x` , 对 `GString`  没有任何影响

如果您需要在 GString 中使用真正的闭包，例如强制执行变量的惰性求值，则需要使用替代语法 `${→ x}` ，如下所示：

[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=gstring_lazy,indent=0]
----

让我们用这段代码来说明它与值可变有何不同：

[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=gstring_mutation,indent=0]
----
<1> `Person` 类有一个 `toString` 方法，返回 `name` 属性
<2> 我们创建了第一个名为 _Sam_ 的 `Person`
<3> 我们创建另一个名为 _Lucy_ 的 `Person`
<4> `p` 变量设置为 `Sam`
<5> 创建了一个闭包，引用 `p` 的值，也就是说 _Sam_
<6> 所以当我们计算字符串时，它返回  _Sam_
<7> 如果我们将 p 更改为 _Lucy_
<8> 该字符串的计算结果仍为 _Sam_ ，因为它是创建 `GString` 时 `p` 的值
<9> 所以如果我们对 _Sam_ 进行修改，将名字改为 _Lucy_
<10> 这次 `GString` 已正确改变

因此，如果您不想依赖可变对象或包装对象，则必须在 `GString` 通过显式声明空参数列表来使用闭包的方式：

[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=gstring_no_mutation,indent=0]
----

== 闭包强制转换

闭包可以转换为接口或单一抽象方法类型。请参阅手册的link:core-semantics.html#closure-coercion[这一部分]以获取完整的说明。


== 函数式编程
闭包是 Groovy 中函数式编程范例的核心。函数上的一些函数式编程操作可直接在 `Closure` 类上使用，如本节中所示。


=== 柯里化

在 Groovy 中，柯里化指的是部分应用的概念。由于 Groovy 对闭包应用了不同的作用域规则，因此它与函数式编程中的柯里化的真正概念并不相符。 Groovy 中的柯里化将允许您设置闭包的一个参数，并且它将返回一个接受少一个参数的新闭包。

==== 左柯里化

左柯里化是指设置闭包最左边的参数，如下例所示：

[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=left_curry,indent=0]
----
<1> `nCopies` 闭包定义了两个参数
<2> `curry` 会将第一个参数设置为 2 ，创建一个接受单个 `String` 的新闭包（函数）
<3> 因此新函数调用只需使用 `String` 即可调用
<4> 等于调用带有两个参数的 `nCopies`

==== 右柯里化

与左柯里化类似，可以设置闭包最右边的参数：

[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=right_curry,indent=0]
----
<1> `nCopies` 闭包定义了两个参数
<2> `rcurry` 将最后一个参数设置为 `bla` ，创建一个接受单个 `int` 的新闭包（函数）
<3> 因此新函数调用只需使用一个 `int` 即可调用
<4> 相当于调用带有两个参数的 `nCopies`

==== 基于索引的柯里化

如果闭包接受超过 2 个参数，则可以使用 `ncurry` 设置任意参数：

[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=ncurry,indent=0]
----
<1> `volume` 函数定义了3个参数
<2> `ncurry` 会将第二个参数 (index = 1) 设置为 `2d` ，创建一个接受l和h的新体积函数
<3> 该函数相当于调用省略了w的 `volume`
<4> 还可以设置多个参数，从指定索引开始
<5> 结果函数接受的参数数量与初始参数减去 `ncurry` 设置的参数数量相同

=== 记忆化

记忆化允许缓存闭包调用的结果。如果函数（闭包）完成的计算很慢，但您知道该函数将经常使用相同的参数调用，那么这很有趣。一个典型的例子是斐波那契套件。一个简单的实现可能如下所示：

[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=naive_fib,indent=0]
----

这是一个幼稚的实现，因为“fib”经常使用相同的参数递归调用，从而导致指数算法：

- 计算 fib(15) 需要 fib(14) 和 fib(13) 的结果
- 计算 fib(14) 需要 fib(13) 和 fib(12) 的结果

由于调用是递归的，您已经可以看到我们将一次又一次地计算相同的值，尽管它们可以被缓存。这种简单的实现可以通过使用 `memoize` 缓存调用结果来“修复”：

[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=memoized_fib,indent=0]
----

WARNING: The cache works *using the actual values of the arguments*. 这意味着如果您将记忆化与原始或装箱原始类型以外的其他类型一起使用，则应该非常小心。

可以使用替代方法调整缓存的行为：

* `memoizeAtMost` 将生成一个新的闭包，最多缓存 n 个值
* `memoizeAtLeast` 将生成一个新的闭包，该闭包缓存至少 n 个值
* `memoizeBetween` will generate a new closure which caches at least n values and at most n values

所有 memoize 变体中使用的缓存都是 LRU 缓存。

=== 闭包组合

闭包组合对应于函数组合的概念(通过组合两个或多个函数（链式调用）)来创建一个新函数，如下例所示：

[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=closure_composition,indent=0]
----

=== Trampoline

递归算法通常受到物理限制的限制：最大堆栈高度。例如，如果您调用一个递归调用自身太深的方法，您最终将收到一个 `StackOverflowException` 。

在这些情况下有帮助的方法是使用 `Closure` 及其 `Trampoline` 功能。


Closures are wrapped in a `TrampolineClosure`. Upon calling, a trampolined `Closure` will call the original `Closure` waiting
for its result. If the outcome of the call is another instance of a `TrampolineClosure`, created perhaps as a result
to a call to the `trampoline()` method, the `Closure` will again be invoked. This repetitive invocation of returned
trampolined Closures instances will continue until a value other than a trampolined `Closure` is returned. That value
will become the final result of the trampoline. That way, calls are made serially, rather than filling the stack.

下面是使用 trampoline() 实现阶乘函数的示例：

[source,groovy]
----
include::../../test/ClosuresSpecTest.groovy[tags=trampoline,indent=0]
----

=== 方法指针

能够使用常规方法作为闭包通常很实用。例如，您可能想要使用闭包的柯里化功能，但这些功能不适用于普通方法。在 Groovy 中，您可以使用link:core-operators.html#method-pointer-operator[方法指针操作符]从任何方法获取闭包。

